### ISSUE TITLE
Feature Request: Extend the tuning to upto 10GB memory

### ISSUE THREAD

**Issue by revolutionisme** [mattymoomoo/aws-power-tuner-ui#5]
As it was recently announced that a lambda container can be created with up to 10GB of memory, it would great to see it reflect in this tool. 

In the app component, I tried editing the max from 30008 to 10240

```
getPowerValues() {
    const increment = 64;
    const powerValues = [];
    for (let value = 128; value <= 10240; value += increment) {
      powerValues.push(value);
    }
    return powerValues;
  }
```
The UI shows all options with 64MB increments and even the lambda gets executed with more than 3008 MB memory, but the final result where it should show the graph comparing cost vs execution time, it threw the following error.

![image](https://user-images.githubusercontent.com/738958/100911458-89d14500-34cf-11eb-89b0-8766fc20cfa9.png)

It feels like the changes must be made on [Matteo's tool](https://github.com/matteo-ronchetti/aws-lambda-power-tuning-ui), but I received the error on the UI so adding this feature request here.

**Comment by mattymoomoo** [comment]
Thank you for the update
